---
- name: Deploy Frontier
  hosts: 10.130.10.237:10.130.127.139:10.130.34.205:10.130.34.210
  remote_user: root
  tasks:
  - name: Activate Interface
    command: ifconfig eth0 up

  - name: Pulling From Github
    git: repo=git@github.com:Bindez/frontier.git dest=/usr/share/jboss-as/standalone/trunk/

  - name: Compiling Package
    command: chdir=/usr/share/jboss-as/standalone/trunk/ /usr/bin/mvn clean package

  - name: Undeploying Current War
    jboss: deploy_path=/usr/share/jboss-as/standalone/deployments/ deployment=ROOT.war state=absent
  
  - name: Remove Old Package
    file: path=/usr/share/jboss-as/standalone/deployments/ROOT.war state=absent

  - name: Deploying New War
    jboss: deploy_path=/usr/share/jboss-as/standalone/deployments/ src=/usr/share/jboss-as/standalone/trunk/target/BindezFrontier-0.0.1-SNAPSHOT.war deployment=ROOT.war state=present

  - name: Deactivate Interface
    command: ifconfig eth0 down         
