---
- hosts: core
  remote_user: root
  vars:
    JAVA_HOME: "/root/jdk1.7.0_67/"
    JRE_HOME: "/root/jdk1.7.0_67/jre/"
  tasks:
  - name: Stop-Solr-Service
    command: sh /root/apache-tomcat-6.0.39/bin/shutdown.sh
  - name: Start-Solr-Service
    command: sh /root/apache-tomcat-6.0.39/bin/startup.sh


